version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    labels: ['dependencies', 't-build']
    schedule:
      interval: 'weekly'
    groups:
      library-bumps:
        patterns: ['*']
        exclude-patterns: ['@biomejs/*']
      biome-bump:
        patterns: ['@biomejs/*']
  - package-ecosystem: 'github-actions'
    directory: '/'
    labels: ['dependencies', 't-ci']
    schedule:
      interval: 'weekly'
    groups:
      ci-bumps:
        patterns: ['*']
  - package-ecosystem: 'npm'
    directory: '/website'
    labels: ['dependencies', 't-build', 'website']
    schedule:
      interval: 'weekly'
    groups:
      website-bumps:
        patterns: ['*']
        exclude-patterns: ['@biomejs/*']
      biome-bump:
        patterns: ['@biomejs/*']
  - package-ecosystem: 'npm'
    directories: ['examples/*']
    labels: ['dependencies', 't-build', 'template']
    schedule:
      interval: 'monthly'
    groups:
      example-deps:
        patterns: ['*']
