version: v1

labels:
  - label: 'website'
    sync: true
    matcher:
      files: 'website/**/*'

  - label: 'pkg-all'
    matcher:
      files: '*'

  - label: 'pkg-bot'
    sync: true
    matcher:
      files: 'packages/bot/**/*'

  - label: 'pkg-client'
    sync: true
    matcher:
      files: 'packages/client/**/*'

  - label: 'pkg-gateway'
    sync: true
    matcher:
      files: 'packages/gateway/**/*'

  - label: 'pkg-rest'
    sync: true
    matcher:
      files: 'packages/rest/**/*'

  - label: 'pkg-types'
    sync: true
    matcher:
      files: 'packages/types/**/*'

  - label: 'pkg-utils'
    sync: true
    matcher:
      files: 'packages/utils/**/*'

  - label: 't-breaking'
    matcher:
      title: "^[a-z]+(\\(.+\\))?!: .*"

  - label: 't-build'
    matcher:
      title: "^build(\\(.+\\))?!?: .*"

  - label: 't-ci'
    matcher:
      files: '.github/workflows/*'
      title: '^ci: .*'

  - label: 't-docs'
    matcher:
      title: "^docs(\\(.+\\))?!?: .*"

  - label: 't-feat'
    matcher:
      title: "^feat(\\(.+\\))?!?: .*"

  - label: 't-fix'
    matcher:
      title: "^fix(\\(.+\\))?!?: .*"

  - label: 't-perf'
    matcher:
      title: "^perf(\\(.+\\))?!?: .*"

  - label: 't-refactor'
    matcher:
      title: "^refactor(\\(.+\\))?!?: .*"

  - label: 't-style'
    matcher:
      title: "^style(\\(.+\\))?!?: .*"

  - label: 't-test'
    matcher:
      title: "^test(\\(.+\\))?!?: .*"
