discordeno/guide:
  - source: site/
    dest: ./
    exclude: |
      README.md
      LICENSE
    deleteOrphaned: true

discordeno/template:
  - source: template/
    dest: ./
    exclude: |
      README.md
      LICENSE
    deleteOrphaned: true
