export enum Errors {
  MISSING_SEND_MESSAGES = "MISSING_SEND_MESSAGES",
  MISSING_MANAGE_ROLES = "MISSING_MANAGE_ROLES",
  MISSING_KICK_MEMBERS = "MISSING_KICK_MEMBERS",
  MISSING_VIEW_CHANNEL = "MISSING_VIEW_CHANNEL",
  MISSING_READ_MESSAGE_HISTORY = "MISSING_READ_MESSAGE_HISTORY",
  MISSING_MANAGE_NICKNAMES = "MISSING_MANAGE_NICKNAMES",
  MISSING_MUTE_MEMBERS = "MISSING_MUTE_MEMBERS",
	MISSING_DEAFEN_MEMBERS = "MISSING_DEAFEN_MEMBERS",
	MISSING_SEND_TTS_MESSAGE = 'MISSING_SEND_TTS_MESSAGE',
	MESSAGE_MAX_LENGTH = 'MESSAGE_MAX_LENGTH',
  NICKNAMES_MAX_LENGTH = "NICKNAMES_MAX_LENGTH"
}
