/** https://discord.com/developers/docs/topics/opcodes-and-status-codes#json */
export enum JsonErrorCodes {
  GeneralError,
  UnknownAccount = 10001,
  UnknownApplication,
  UnknownChannel,
  UnknownGuild,
  UnknownIntegration,
  UnknownInvite,
  UnknownMember,
  UnknownMessage,
  UnknownPermissionOverwrite,
  UnknownProvider,
  UnknownRole,
  UnknownToken,
  UnknownUser,
  UnknownEmoji,
  UnknownWebhook,
  UnknownWebhookService,
  UnknownSession = 10020,
  UnknownBan = 10026,
  UnknownSKU,
  UnknownStoreListing,
  UnknownEntitlement,
  UnknownBuild,
  UnknownLobby,
  UnknownBranch,
  UnknownStoreDirectoryLayout,
  UnknownRedistributable = 10036,
  UnknownGiftCode = 10038,
  UnknownStream = 10049,
  UnknownPremiumServerSubscribeCooldown,
  UnknownGuildTemplate = 10057,
  UnknownDiscoveryCategory = 10059,
  UnknownSticker,
  UnknownInteraction = 10062,
  UnknownApplicationCommand = 10063,
  UnknownApplicationCommandPermissions = 10066,
  UnknownStageInstance,
  UnknownGuildMemberVerificationForm,
  UnknownGuildWelcomeScreen,
  UnknownGuildScheduledEvent,
  UnknownGuildScheduledEventUser,
  BotsCannotUseThisEndpoint = 20001,
  OnlyBotsCanUseThisEndpoint,
  ExplicitContentCannotBeSentToTheDesiredRecipient = 20009,
  YouAreNotAuthorizedToPerformThisActionOnThisApplication = 20012,
  ThisActionCannotBePerformedDueToSlowmodeRateLimit = 20016,
  OnlyTheOwnerOfThisAccountCanPerformThisAction = 20018,
  ThisMessageCannotBeEditedDueToAnnouncementRateLimits = 20022,
  TheChannelYouAreWritingHasHitTheWriteRateLimit = 20028,
  TheWriteActionYouArePerformingOnTheServerHasHitTheWriteRateLimit,
  YourStageTopicOrServerNameOrServerDescriptionOrChannelNamesContainsWordsThatAreNotAllowedForPublicStages = 20031,
  GuildPremiumSubscriptionLevelTooLow = 20035,
  MaximumNumberOfGuildsReached = 30001,
  MaximumNumberOfFriendsReached,
  MaximumNumberOfPinsReachedForTheChannel,
  MaximumNumberOfRecipientsReached,
  MaximumNumberOfGuildRolesReached,
  MaximumNumberOfWebhooksReached = 30007,
  MaximumNumberOfEmojisReached,
  MaximumNumberOfReactionsReached = 30010,
  MaximumNumberOfGuildChannelsReached = 30013,
  MaximumNumberOfAttachmentsInAMessageReached = 30015,
  MaximumNumberOfInvitesReached,
  MaximumNumberOfAnimatedEmojisReached = 30018,
  MaximumNumberOfServerMembersReached,
  MaximumNumberOfServerCategoriesHasBeenReached = 30030,
  GuildAlreadyHasTemplate = 30031,
  MaxNumberOfThreadParticipantsHasBeenReached = 30033,
  MaximumNumberOfBansForNonGuildMembersHaveBeenExceeded = 30035,
  MaximumNumberOfBansFetchesHasBeenReached = 30037,
  MaximumNumberOfUncompletedGuildScheduledEventsReached = 30038,
  MaximumNumberOfStickersReached = 30039,
  MaximumNumberOfPruneRequestsHasBeenReachedTryAgainLater,
  MaximumNumberOfGuildWidgetSettingsUpdatesHasBeenReachedTryAgainLater = 30042,
  UnauthorizedProvideAValidTokenAndTryAgain = 40001,
  YouNeedToVerifyYourAccountInOrderToPerformThisAction,
  YouAreOpeningDirectMessagesTooFast,
  RequestEntityTooLargeTrySendingSomethingSmallerInSize = 40005,
  ThisFeatureHasBeenTemporarilyDisabledServerSide,
  ThisUserBannedFromThisGuild,
  TargetUserIsNotConnectedToVoice = 40032,
  ThisMessageHasAlreadyBeenCrossposted = 40033,
  AnApplicationCommandWithThatNameAlreadyExists = 40041,
  MissingAccess = 50001,
  InvalidAccountType,
  CannotExecuteActionOnADMChannel,
  GuildWidgetDisabled,
  CannotEditMessageAuthoredByAnotherUser,
  CannotSendAnEmptyMessage,
  CannotSendMessagesToThisUser,
  CannotSendMessagesInAVoiceChannel,
  ChannelVerificationLevelIsTooHighForYouToGainAccess,
  OAuth2ApplicationDoesNotHaveABot,
  OAuth2ApplicationLimitReached,
  InvalidOAuth2State,
  YouLackPermissionsToPerformThatAction,
  InvalidAuthenticationTokenProvided,
  NoteWasTooLong,
  ProvidedTooFewOrTooManyMessagesToDeleteMustProvideAtLeast2AndFewerThan100MessagesToDelete,
  AMessageCanOnlyBePinnedInTheChannelItWasSentIn = 50019,
  InviteCodeWasEitherInvalidOrTaken,
  CannotExecuteActionOnASystemMessage,
  CannotExecuteActionOnThisChannelType = 50024,
  InvalidOAuth2AccessTokenProvided,
  MissingRequiredOAuth2Scope,
  InvalidWebhookTokenProvided,
  InvalidRole,
  InvalidRecipients = 50033,
  AMessageProvidedWasTooOldToBulkDelete,
  InvalidFormBodyOrContentTypeProvided,
  AnInviteWasAcceptedToAGuildTheApplicationsBotIsNotIn,
  InvalidApiVersionProvided = 50041,
  FileUploadedExceedsTheMaximumSize = 50045,
  InvalidFileUploaded,
  CannotSelfRedeemThisGift = 50054,
  InvalidGuild,
  PaymentSourceRequiredToRedeemGift = 50070,
  CannotDeleteAChannelRequiredForCommunityGuilds = 50074,
  InvalidStickerSent = 50081,
  TriedToPerformAnOperationOnAnArchivedThreadSuchAsEditingAMessageOrAddingAUserToTheThread = 50083,
  InvalidThreadNotificationSettings,
  BeforeValueIsEarlierThanTheThreadCreationDate,
  ThisServerIsNotAvailableInYourLocation = 50095,
  ThisServerNeedsMonetizationEnabledInOrderToPerformThisAction = 50097,
  ThisServerNeedsMoreBoostsToPerformThisAction = 50101,
  TheRequestBodyContainsInvalidJSON = 50109,
  TwoFactorIsRequiredForThisOperation = 60003,
  NoUsersWithDiscordTagExist = 80004,
  ReactionWasBlocked = 90001,
  ApiResourceIsCurrentlyOverloadedTryAgainALittleLater = 130000,
  TheStageIsAlreadyOpen = 150006,
  CannotReplyWithoutPermissionToReadMessageHistory = 160002,
  AThreadHasAlreadyBeenCreatedForThisMessage = 160004,
  ThreadIsLocked = 160005,
  MaximumNumberOfActiveThreadsReached = 160006,
  MaximumNumberOfActiveAnnouncementThreadsReached = 160007,
  InvalidJsonForUploadedLottieFile = 170001,
  UploadedLottiesCannotContainRasterizedImagesSuchAsPngOrJpeg,
  StickerMaximumFramerateExceeded,
  StickerFrameCountExceedsMaximumOf1000Frames,
  LottieAnimationMaximumDimensionsExceeded,
  StickerFrameRateIsEitherTooSmallOrTooLarge,
  StickerAnimationDurationExceedsMaximumOf5Seconds,
  CannotUpdateAFinishedEvent = 180000,
  FailedToCreateStageNeededForStageEvent = 180002,
}
