import {
  c1amelize1Activity,
  c1amelize1AllowedMentions,
  c1amelize1Application,
  c1amelize1ApplicationCommand,
  c1amelize1ApplicationCommandOption,
  c1amelize1ApplicationCommandOptionChoice,
  c1amelize1ApplicationCommandPermission,
  c1amelize1Attachment,
  c1amelize1AutoModerationActionExecution,
  c1amelize1AutoModerationRule,
  c1amelize1Channel,
  c1amelize1Component,
  c1amelize1Embed,
  c1amelize1Emoji,
  c1amelize1GatewayBot,
  c1amelize1Guild,
  c1amelize1Member,
  c1amelize1Message,
  c1amelize1Role,
  c1amelize1Sticker,
  c1amelize1Team,
  c1amelize1User,
  c1amelize1Webhook,
  c1amelize1WelcomeScreen,
  c1amelize1Widget,
  c1amelize1WidgetSettings
} from './camel/index.js'
import {
  s1nakelize1Activity,
  s1nakelize1AllowedMentions,
  s1nakelize1Application,
  s1nakelize1ApplicationCommand,
  s1nakelize1ApplicationCommandOption,
  s1nakelize1ApplicationCommandOptionChoice,
  s1nakelize1ApplicationCommandPermission,
  s1nakelize1Attachment,
  s1nakelize1AutoModerationActionExecution,
  s1nakelize1AutoModerationRule,
  s1nakelize1Channel,
  s1nakelize1Component,
  s1nakelize1Embed,
  s1nakelize1Emoji,
  s1nakelize1GatewayBot,
  s1nakelize1Guild,
  s1nakelize1InteractionResponse,
  s1nakelize1Member,
  s1nakelize1Message,
  s1nakelize1Role,
  s1nakelize1Sticker,
  s1nakelize1Team,
  s1nakelize1User,
  s1nakelize1Webhook,
  s1nakelize1WelcomeScreen,
  s1nakelize1Widget,
  s1nakelize1WidgetSettings
} from './snake/index.js'

export * from './camel/index.js'
export * from './snake/index.js'

export const TRANSFORMERS = {
  activity: c1amelize1Activity,
  allowedMentions: c1amelize1AllowedMentions,
  application: c1amelize1Application,
  command: c1amelize1ApplicationCommand,
  commandOption: c1amelize1ApplicationCommandOption,
  commandOptionChoice: c1amelize1ApplicationCommandOptionChoice,
  commandPermission: c1amelize1ApplicationCommandPermission,
  attachment: c1amelize1Attachment,
  automodActionExecution: c1amelize1AutoModerationActionExecution,
  automodRule: c1amelize1AutoModerationRule,
  channel: c1amelize1Channel,
  component: c1amelize1Component,
  embed: c1amelize1Embed,
  emoji: c1amelize1Emoji,
  gatewayBot: c1amelize1GatewayBot,
  guild: c1amelize1Guild,
  user: c1amelize1User,
  member: c1amelize1Member,
  message: c1amelize1Message,
  role: c1amelize1Role,
  sticker: c1amelize1Sticker,
  team: c1amelize1Team,
  webhook: c1amelize1Webhook,
  welcomeScreen: c1amelize1WelcomeScreen,
  widget: c1amelize1Widget,
  widgetSettings: c1amelize1WidgetSettings,

  reverse: {
    activity: s1nakelize1Activity,
    allowedMentions: s1nakelize1AllowedMentions,
    application: s1nakelize1Application,
    command: s1nakelize1ApplicationCommand,
    commandOption: s1nakelize1ApplicationCommandOption,
    commandOptionChoice: s1nakelize1ApplicationCommandOptionChoice,
    commandPermission: s1nakelize1ApplicationCommandPermission,
    attachment: s1nakelize1Attachment,
    automodActionExecution: s1nakelize1AutoModerationActionExecution,
    automodRule: s1nakelize1AutoModerationRule,
    channel: s1nakelize1Channel,
    component: s1nakelize1Component,
    embed: s1nakelize1Embed,
    emoji: s1nakelize1Emoji,
    gatewayBot: s1nakelize1GatewayBot,
    guild: s1nakelize1Guild,
    interactionResponse: s1nakelize1InteractionResponse,
    user: s1nakelize1User,
    member: s1nakelize1Member,
    message: s1nakelize1Message,
    role: s1nakelize1Role,
    sticker: s1nakelize1Sticker,
    team: s1nakelize1Team,
    webhook: s1nakelize1Webhook,
    welcomeScreen: s1nakelize1WelcomeScreen,
    widget: s1nakelize1Widget,
    widgetSettings: s1nakelize1WidgetSettings
  }
}

export default TRANSFORMERS
