rest:
	deno run -A --unstable --import-map ./importMap.json rest/mod.ts

gateway:
	deno run -A --unstable --import-map ./importMap.json src/gateway/mod.ts

bot:
	deno run -A --unstable --import-map ./importMap.json src/bot/mod.ts