/** https://discord.com/developers/docs/resources/channel#channel-object-channel-structure */
export interface ChannelPayload {
    /** the id of this channel */
    id: string;
    /** the type of channel */
    type: ChannelTypes;
    /** the id of the guild */
    guild_id?: string;
    /** sorting position of the channel */
    position?: number;
    /** explicit permission overwrites for members and roles */
    permission_overwrites?: OverwritePayload[];
    /** the name of the channel (2-100 characters) */
    name?: string;
    /** the channel topic (0-1024 characters) */
    topic?: string | null;
    /** whether the channel is nsfw */
    nsfw?: boolean;
    /** the id of the last message sent in this channel (may not point to an existing or valid message) */
    last_message_id?: string | null;
    /** the bitrate (in bits) of the voice channel */
    bitrate?: number;
    /** the user limit of the voice channel */
    user_limit?: number;
    /** amount of seconds a user has to wait before sending another message (0-21600); bots, as well as users with the permission manage_messages or manage_channel, are unaffected */
    rate_limit_per_user?: number;
    /** the recipients of the DM */
    recipients?: UserPayload[];
    /** icon hash */
    icon?: string | null;
    /** id of the DM creator */
    owner_id?: string;
    /** application id of the group DM creator if it is bot-created */
    application_id?: string;
    /** id of the parent category for a channel (each parent category can contain up to 50 channels) */
    parent_id?: string | null;
    /** when the last pinned message was pinned. This may be null in events such as GUILD_CREATE when a message is not pinned. */
    last_pin_timestamp?: string | null;
}

/** https://discord.com/developers/docs/resources/channel#channel-object-channel-types */
export enum ChannelTypes {
    /** a text channel within a server */
    GUILD_TEXT,
    /** a direct message between users */
    DM,
    /** a voice channel within a server */
    GUILD_VOICE,
    /** a direct message between multiple users */
    GROUP_DM,
    /** an organizational category that contains up to 50 channels */
    GUILD_CATEGORY,
    /** a channel that users can follow and crosspost into their own server */
    GUILD_NEWS,
    /** a channel in which game developers can sell their game on Discord */
    GUILD_STORE,
}

/** https://discord.com/developers/docs/resources/channel#message-object-message-structure */
export interface MessagePayload {
    /** id of the message */
    id: string;
    /** id of the channel the message was sent in */
    channel_id: string;
    /** id of the guild the message was sent in */
    guild_id?: string;
    /** the author of this message (not guaranteed to be a valid user) */
    user: UserPayload;
    /** member properties for this message's author */
    member?: PartialGuildMemberPayload;
    /** contents of the message */
    content: string;
    /** when this message was sent */
    timestamp: string;
    /** when this message was edited (or null if never) */
    edited_timestamp: string | null;
    /** whether this was a TTS message */
    tts: boolean;
    /** whether this message mentions everyone */
    mention_everyone: boolean;
    /** users specifically mentioned in the message */
    mentions: UserPayload & Partial<GuildMemberPayload>;
    /** roles specifically mentioned in this message */
    mention_roles: string[];
    /** channels specifically mentioned in this message */
    mention_channels?: ChannelMentionPayload[];
    /** any attached files */
    attachments: AttachmentPayload[];
    /** any embedded content */
    embeds: EmbedPayload[];
    /** reactions to the message */
    reactions?: ReactionPayload[];
    /** used for validating a message was sent */
    nonce?: number | string;
    /** whether this message is pinned */
    pinned: boolean;
    /** if the message is generated by a webhook, this is the webhook's id */
    webhook_id?: string;
    /** type of message */
    type: MessageTypes;
    /** sent with Rich Presence-related chat embeds */
    activity?: MessageActivitypayload
}