import { DiscordAttachment } from "../../lib/structures/message/attachment.ts";
import { DiscordEmbed } from "../../lib/structures/message/embed/embed.ts";
import { DiscordReaction } from "../../lib/structures/message/reaction.ts";
import { DiscordUser } from "../member/user/user.ts";
import { DiscordMessageActivity } from "./activity/activity.ts";
import { DiscordMessageSticker } from "./stickers/sticker.ts";
import { DiscordMessageFlags } from "./flags.ts";
import { DiscordMessageTypes } from "./type.ts";
import { DiscordMessageReference } from "./reference.ts";
import { DiscordMessageApplication } from "./application.ts";
import { DiscordChannelMention } from "./channel.ts";
import { DiscordBaseMember } from "../member/base.ts";
import { DiscordMember } from "../member/member.ts";

/** https://discord.com/developers/docs/resources/channel#message-object-message-structure */
export interface DiscordMessage {
  /** id of the message */
  id: string;
  /** id of the channel the message was sent in */
  // deno-lint-ignore camelcase
  channel_id: string;
  /** id of the guild the message was sent in */
  // deno-lint-ignore camelcase
  guild_id?: string;
  /** the author of this message (not guaranteed to be a valid user) */
  author: DiscordUser;
  /** member properties for this message's author */
  member?: DiscordBaseMember;
  /** contents of the message */
  content: string;
  /** when this message was sent */
  timestamp: string;
  /** when this message was edited (or null if never) */
  // deno-lint-ignore camelcase
  edited_timestamp: string | null;
  /** whether this was a TTS message */
  tts: boolean;
  /** whether this message mentions everyone */
  // deno-lint-ignore camelcase
  mention_everyone: boolean;
  /** users specifically mentioned in the message */
  mentions: (DiscordUser & Partial<DiscordMember>)[];
  /** roles specifically mentioned in this message */
  // deno-lint-ignore camelcase
  mention_roles: string[];
  /** channels specifically mentioned in this message */
  // deno-lint-ignore camelcase
  mention_channels?: DiscordChannelMention[];
  /** any attached files */
  attachments: DiscordAttachment[];
  /** any embedded content */
  embeds: DiscordEmbed[];
  /** reactions to the message */
  reactions?: DiscordReaction[];
  /** used for validating a message was sent */
  nonce?: number | string;
  /** whether this message is pinned */
  pinned: boolean;
  /** if the message is generated by a webhook, this is the webhook's id */
  // deno-lint-ignore camelcase
  webhook_id?: string;
  /** type of message */
  type: DiscordMessageTypes;
  /** sent with Rich Presence-related chat embeds */
  activity?: DiscordMessageActivity;
  /** sent with Rich Presence-related chat embeds */
  application?: DiscordMessageApplication;
  /** reference data sent with crossposted messages and replies */
  // deno-lint-ignore camelcase
  message_reference?: DiscordMessageReference;
  /** message flags combined as a bitfield */
  flags?: DiscordMessageFlags;
  /** the stickers sent with the message (bots currently can only receive messages with stickers, not send) */
  stickers?: DiscordMessageSticker[];
  /** the message associated with the `message_reference` */
  // deno-lint-ignore camelcase
  referenced_message?: DiscordMessage | null;
}
