#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if git diff-tree -r --name-only --no-commit-id HEAD@{1} HEAD | grep -q "yarn\|package.json"; then
  echo "hook(post-merge) - Found changes to a yarn file or package.json, running Yarn."
  yarn
fi
