name: Labeler

on:
  pull_request_target:
    types: ['edited', 'opened', 'reopened', 'synchronize']

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    steps:
      - uses: fuxingloh/multi-labeler@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
