name: Labeler
permissions:
  issues: write
  pull-requests: write
on:
  pull_request_target:
    types: ['edited', 'opened', 'reopened', 'synchronize']
  issues:
    types: ['opened', 'reopened']

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_target'
    steps:
      - uses: fuxingloh/multi-labeler@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
