name: Lint
on: 
  push:
    paths:
      - 'src/**'
  pull_request:
    paths:
      - 'src/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
      - name: Run format script with --check
        run: deno fmt --ignore=./docs --check
