name: Lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
      - name: Run fmt check script
        run: deno fmt --check --ignore=./src/types/util.ts
      - name: Run lint script
        run: deno lint src/** test/** --unstable
