name: Lint
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@master
      - name: Cache dependencies
        run: deno cache mod.ts
      - name: Format TypeScript files
        run: deno fmt *.ts --check
