name: Test Docusaurus build

on:
  pull_request:
    paths:
      - "site/**"

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: npm
          cache-dependency-path: site/package-lock.json
      - name: Test build
        working-directory: site
        run: |
          npm ci
          npm run build
