name: Test Docusaurus build

on:
  pull_request:
    paths:
      - "docs/**"

defaults:
  run:
    working-directory: site

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: npm
      - name: Test build
        run: |
          npm ci
          npm run build
