name: Test
on: 
  push:
    branches: master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
      - name: Cache dependencies
        run: deno cache mod.ts
      - name: Run test script
        run: deno test --allow-net --allow-env
    env:
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
