name: Test
on: [push, pull_request]
jobs:
  test:
    if: github.event.label.name == 'run-tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
      - name: Run test script
        run: deno test --allow-net --allow-env
    env:
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
